[package]
name = "ploxion-port-80"
description = "WASM ploxion: le port 80 (http) en ploxion (port-bion). Residu PortDef + port_ploxion!. Reseau-en-ploxions."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ploxion-sdk = { path = "../sdk" }
