[package]
name = "ploxion-pkg-git"
description = "WASM ploxion: le paquet git en ploxion (package-bion). Residu PackageDef + package_ploxion!. Reseau/systeme-en-ploxions (bion-Linux)."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ploxion-sdk = { path = "../sdk" }
